### PR TITLE
use .spec.ingressClassName in HTTPProxy test

### PR DESCRIPTION
**Pull request by umezawatakeshi**
forgot to update test code.

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

### CODE REVIEW

**Comment by morimoto-cybozu** [comment]
@umezawatakeshi 
This data file is just for creating HTTPProxy, not for testing the admission webhook around HTTPProxy.  And there are many other test-data files which uses `kubernetes.io/ingress.class` annotation.
Although updating data files to a newer format has its own worth, updating `admission_test.go` would be appropriate to update the tests about the admission webhook.

**Comment by umezawatakeshi** [comment]
Tests around admission webhook is already updated in https://github.com/cybozu-go/neco-apps/pull/1780 (https://github.com/cybozu-go/neco-apps/pull/1780/commits/d3c60aabff9da0a2ff3051381fadee88f45ccb27). So "forgot to update test **code**." may not a correct wording...

Anyway, I will update test-data files to use `.spec.ingressClassName`. Is it OK?

**Comment by morimoto-cybozu** [comment]
@umezawatakeshi 
I'll make an explicit reply.

> Tests around admission webhook is already updated in #1780 (d3c60aa).

Ah, I overlooked it.

> Anyway, I will update test-data files to use `.spec.ingressClassName`. Is it OK?

Sure, please.

**Comment by umezawatakeshi** [comment]
@morimoto-cybozu 

As I was modifying the test-data, I noticed that the `HTTPProxy`s in test-data must declare ingress classes in the same way as the one in the main manifests to test correctly. So now I don't think I should change them to use `.spec.ingressClassName` fields.

Currently, neco-admission doesn't support the migration from `kubernetes.io/ingress.class` annotation to `.spec.ingressClassName` field, so we can't change the main manifests either.

**Comment by morimoto-cybozu** [comment]
@umezawatakeshi 
Well, will you close this PR?  Or freeze this until neco-admission supports migration?

**Comment by umezawatakeshi** [comment]
@morimoto-cybozu 
I still wonder whether we should update manifests used by contour_test.go. What do you think?

**Comment by morimoto-cybozu** [comment]
@umezawatakeshi 
If the set of the manifests used by contour_test.go is a subset of the production manifests set, we cannot update them until neco-admission supports migration, as you wrote.

It the manifests used by contour_test.go are independent of the production manifests, we can either update them immediately or defer update.
Anyway we should update them at some future time because the annotation style will be deprecated and may be removed eventually.

**Review by morimoto-cybozu — APPROVED** [review]
LGTM

**Pull request merged**
