### PR TITLE
Update MOCO to 0.10.8 (chart: 0.1.1)

### PR DESCRIPTION
**Pull request by masa213f**
Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

### CODE REVIEW

**Review by yokaze — CHANGES_REQUESTED** [review]
> Update MOCO to 0.10.8 (chart: 0.1.0)

The chart should be 0.1.1?

**Comment by masa213f** [comment]
@yokaze 
Thank you! I fixed the commit message.

**Review by yokaze — CHANGES_REQUESTED** [review]
I found that `overlays/stage0` is broken. Please take a look.

```
$ kustomize build base | yq e 'select(.metadata.name=="moco") | .spec.source' -
chart: moco
helm:
  version: v3
repoURL: https://cybozu-go.github.io/moco
targetRevision: 0.1.0
```

```
$ kustomize build overlays/stage0 | yq e 'select(.metadata.name=="moco") | .spec.source' -
chart: moco
helm:
  version: v3
repoURL: https://cybozu-go.github.io/moco
targetRevision: stage
```

**Review by yokaze — APPROVED** [review]
LGTM

**Pull request merged**
