### PR TITLE
use AvailableReplicas instead of ReadyReplicas

### PR DESCRIPTION
**Pull request by umezawatakeshi**
`AvailableReplicas` in StatefulSetStatus is available since k8s 1.22. It is more preferable than ReadyReplicas.

Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

### CODE REVIEW

**Comment by morimoto-cybozu** [comment]
@umezawatakeshi 
Can we replace `ReadyReplicas` in test/reboot_test.go?
Should we leave them unchanged?

**Comment by umezawatakeshi** [comment]
It seems preferable to replace ReadyReplicas in test/reboot_test.go.

**Review by morimoto-cybozu — APPROVED** [review]
LGTM

**Review by morimoto-cybozu — APPROVED** [review]
LGTM

**Pull request merged**
