### PR TITLE
team-management: add dbre team and app-cybozu-com-mysql namespace

### PR DESCRIPTION
**Pull request by yokaze**
This PR adds dbre team and app-cybozu-com-mysql namespace.

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

### CODE REVIEW

**Review by zoetrope — COMMENTED** [review]
Is the addition of `app-cybozu-com-mysql` namespace another PR?

**Comment by yokaze** [comment]
@zoetrope I'm not sure that I can add an team and a namespace simultaneously... Can I do that?

**Comment by zoetrope** [comment]
@yokaze 
I don't think it will be a problem.
What problems are you worried about?

**Comment by yokaze** [comment]
@zoetrope 
I didn't worry about any specific limitation, I just felt they are two distinct operations.
However the CI does not assume a team without any namespace.. I found I need to add them simultaneously.

**Review by zoetrope — APPROVED** [review]
LGTM

**Pull request merged**
